### PR TITLE
Add form to delete orphaned entities

### PR DESCRIPTION
**Pull request by almasaeed2010**
This PR adds a form to allow for the deletion of entities that are missing chado records. This acts as an `unpublish` method for cases when the chado record is deleted but the entity didn't get deleted.

### Testing

The form is super simple. Single element with a list of bundles that have orphaned entities. Select the bundle and hit submit then run the job. The entities will get delete and hooks for the deletion will get triggered. This job may take a while to complete depending on the number of orphaned entities.

To set up a scenario where you can test this on a dev site:
1. Create an organism using the GUI
1. Delete the organism from chado.organism
1. Visit the new form page and see that there is 1 orphaned organism entity

### CODE REVIEW

**Comment by almasaeed2010** [comment]
Note that this also adds a new page to list the menu items that are provided by this module. This page server like an index for all available operations and is populated automatically when the `tripal_alchemist_menu` hook is modified.

**Comment by almasaeed2010** [comment]
The code currently takes a long time for large tables such as `mRNA`. In fact, it never returned the results for that bundle even after waiting for 20 minutes. We are gonna need to add more filters or find another query.

**Comment by almasaeed2010** [comment]
It's hard to create a progress bar for this in the job output because we are bombarded with errors like these:

```[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_select_record: the foreign key definition for 'analysisfeature_id' on table 'analysisfeatureprop' returned no results where the definition supplied was Array(    [feature_id] => )
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Missing $object argument to the chado_expand_var function from load (line: 230)
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_select_record: the foreign key definition for 'analysisfeature_id' on table 'analysisfeatureprop' returned no results where the definition supplied was Array(    [feature_id] => )
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Missing $object argument to the chado_expand_var function from tripal_chado_field_storage_load (line: 408)
```

This is expected since it has to load the entity to be able to delete it (drupal rules) and most fields expect the chado record data to be present. In this case, the record doesn't exist altogether. There is no proper way to avoid this without going through all the fields and make sure they don't make the assumption that the chado record is available by default. Too much work that involves checking modules that don't belong to us!

**Comment by almasaeed2010** [comment]
We should probably get the top 10 results to show an excerpt of what's missing in Chado.

**Comment by almasaeed2010** [comment]
We encountered a fatal error on the main dev after a little while:

```
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Missing $object argument to the chado_expand_var function from tripal_chado_field_storage_load (line: 408)
Could not update the bundle menu because that field already exists.  [error]
Job execution failed: SQLSTATE[22001]: String data, right truncated: [error]
7 ERROR:  value too long for type character varying(32)
Job execution failed: Unable to find selected entities while         [error]
attempting to delete orphaned entities.
```

I am not sure what this means.

**Comment by almasaeed2010** [comment]
Reran the job and it's executing as expected again.

**Comment by almasaeed2010** [comment]
Ok this is ready for merging. I tested this on local, main dev and live. If you'd like to take a look at it @bradfordcondon, maybe UI enhancements or more features, let me know.

**Comment by bradfordcondon** [comment]
```
Calling: tripal_alchemist_delete_orphaned_entities(7)
Found 1 orphaned entities.
Job execution failed: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens      [error]
```

deleting a chado record for a single mRNA and running the orphan killer gives me the above error

**Pull request merged**
